[tool.poetry]
name = "quant-trading"
version = "0.1.0"
description = ""
authors = ["Jong Yoon Kim <jongyoon@neuroflex.io>"]
readme = "README.md"
packages = [{include = "quant_trading"}]

[tool.poetry.dependencies]
python = ">=3.11"
lxml = ">=4.9.0"
beautifulsoup4 = "^4.12.2"
requests = "^2.31.0"
pandas = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
