"""add stock columns

Revision ID: add_stock_columns
Revises: 333f3457a65d
Create Date: 2024-03-21 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "add_stock_columns"
down_revision: Union[str, None] = "333f3457a65d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stocks", sa.Column("industry", sa.String(length=100), nullable=True))
    op.add_column(
        "stocks",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    )
    op.alter_column("stocks", "market", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "stocks", "last_updated", existing_type=sa.DateTime(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stocks", "last_updated", existing_type=sa.DateTime(), nullable=True
    )
    op.alter_column("stocks", "market", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("stocks", "is_active")
    op.drop_column("stocks", "industry")
    # ### end Alembic commands ###
