"""add market field to stocks table

Revision ID: add_market_field_to_stocks
Revises: de8849e4c337
Create Date: 2024-03-21 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "add_market_field_to_stocks"
down_revision: Union[str, None] = "de8849e4c337"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stocks", sa.Column("market", sa.String(), nullable=True))
    op.create_index(op.f("ix_stocks_market"), "stocks", ["market"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stocks_market"), table_name="stocks")
    op.drop_column("stocks", "market")
    # ### end Alembic commands ###
