"""create stocks table

Revision ID: de8849e4c337
Revises: 401a0f1d9993
Create Date: 2025-05-08 01:51:41.041999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de8849e4c337"
down_revision: Union[str, None] = "401a0f1d9993"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stocks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stocks_country"), "stocks", ["country"], unique=False)
    op.create_index(op.f("ix_stocks_id"), "stocks", ["id"], unique=False)
    op.create_index(op.f("ix_stocks_name"), "stocks", ["name"], unique=False)
    op.create_index(op.f("ix_stocks_ticker"), "stocks", ["ticker"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stocks_ticker"), table_name="stocks")
    op.drop_index(op.f("ix_stocks_name"), table_name="stocks")
    op.drop_index(op.f("ix_stocks_id"), table_name="stocks")
    op.drop_index(op.f("ix_stocks_country"), table_name="stocks")
    op.drop_table("stocks")
    # ### end Alembic commands ###
